robot:
  # Publish all joint states -----------------------------------
  joint_state_controller:
    type: joint_state_controller/JointStateController
    publish_rate: 50  

  # Position Controllers ---------------------------------------
  joint1_effort_controller:
    type: effort_controllers/JointEffortController
    joint: base_cylinder_joint
    pid: {p: 100.0, i: 0.01, d: 10.0}
  joint2_effort_controller:
    type: effort_controllers/JointEffortController
    joint: lower_cylinder2_joint
    pid: {p: 100.0, i: 0.01, d: 10.0}
 